spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.132:3306/sell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
env:
  test33
girl:
  name: haha
  age: 33
