spring:
  application:
    name: order
  redis:
    host: 192.168.25.128
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.133:3306/sell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 192.168.25.128
    port: 5672
    username: guest
    password: guest
env:
  test11
girl:
  name: haha
  age: 11
